# -*- coding: utf-8 -*-
"""SE01 Data Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPBkbEHli2LpgcSZDmRNirQu_icjWaw2
"""
# start of program
import random

# Define the data model
# Set up first the tasks
# In order to set up tasks, we need to differentiate between word tasks and text tasks
# So we first define words
print("==========Words============")

Words = [["kläder", 'NO'],
         ["en", 'AR'],
         ["t-shirt", 'NO'],
         ["t-shirtar", 'NO'],
         ["tröja", 'NO'],
         ["tröjor", 'NO'],
         ["skjorta", 'NO'],
         ["skjortor", 'NO'],
         ["blus", 'NO'],
         ["blusar", 'NO'],
         ["ett", 'AR'],
         ["linne", 'NO'],
         ["gul", 'AD'],
         ["gula", 'AD'],
         ["gult", 'AD'],
         ["röd", 'AD'],
         ["röda", 'AD']]

print(Words)

# With the words, we can now create word tasks as lists of words
print("==========Tasks============")

T001 = [Words[1][0],Words[12][0],Words[6][0]]
print(T001)
T002 = [Words[16][0], Words[9][0]]
print(T002)
T003 = [Words[10][0], Words[11][0]]
print(T003)
# We can also set up text tasks
T004 = "en gul t-shirt"
print(T004)
T005 = "gula t-shirtar"
print(T005)
T006 = "ett gult linne"
print(T006)

# Now we can combine takss into exercises where we can combine both types of tasks
print("==========Exercises============")

E001 = [T001, T002, T006]
print(E001)
E002 = [T001, T005,T002]
print(E002)
E003 = [T001, T002,T003,T004]
print(E003)

# Now we can set up Lessons"
print("==========Lessons============")
L1 = [E001, E002, E003]
print(L1)
L2 = [E002, E001, E003]
print(L2)

# Finally we can defien the full course
print("==========Course===========")
Course = [L1, L2]
print(Course)
#print (len(Words))

# function to return 3 nouns that are different from the nouns in list_NO
def give_noons(list_NO):
    given_NO = []
    # Get all words that are :
    #   - Nouns
    #   - not in list_NO
    for j in range(len(Words)):
        if Words[j][1] == 'NO' and Words[j][0] not in list_NO:
            given_NO.append(Words[j][0])
    # Retrieve 3 random samples from list
    given_NO = random.sample(given_NO, 3)
    return given_NO

list = ['kläder', 'Kvinna']
given = give_noons(list)
print(given)

# function to return 3 adjectives that are different from the adjectives in list_AD
def give_adjectives(list_AD):
    given_AD = []
    # Get all words that are :
    #   - adjectives
    #   - not in list_AD
    for j in range(len(Words)):
        if Words[j][1] == 'AD' and Words[j][0] not in list_AD:
            given_AD.append(Words[j][0])
    # Retrieve 3 random samples from list
    given_AD = random.sample(given_AD, 3)
    return given_AD

list = ['gul']
given = give_adjectives(list)
print(given)

# function to verify that task is correct in Lesson , Exercise , Task "
def verify(lesson, exercise, task, answer):
    LES = Course[lesson]
    EX = LES[exercise]
    TASK = EX[task]
    if TASK == answer:
        status = 'CORRECT'
    else:
        status = 'INCORRECT'
    return status

ctl = verify(0, 0, 0, ['en', 'gull', 'skjorta'])
print(ctl)

